openapi: 3.0.0

info:
  version: v0.1.0
  title: Trial work APIs

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

components:

  parameters:
    offsetParam:
      in: query
      name: offset
      required: false
      schema:
        type: integer
        minimum: 0
      description: The offset to start collecting the data from.

    limitParam:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
      description: Numbers of items to be returned.

    sortParam:
      in: query
      name: sort
      required: false
      schema:
        type: string
      description: Sort property, if the sort property starts with `<` it will sort in ASC, or `>` it will sort in DESC.

    filterParam:
      in: query
      name: filter
      required: false
      schema:
        type: string
      description: RSQL queries filtration.

  responses:
    Error:
      description: Error happened
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      properties:
        code:
          type: string
          description: Error code.
        message:
          type: string
          description: Error message.

paths:
